name: map_enhancer
description: A plugin which extends Dart's native `Map` type with a couple of handy methods.
version: 2.0.0
homepage: https://github.com/crizant/dart_map_enhancer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
